TARGET_BOX_DIAGONAL_PX = 350

CROP_HEIGHT_PX = 2000
CROP_ASPECT_WIDTH = 9
CROP_ASPECT_HEIGHT = 16
CROP_WIDTH_PX = CROP_HEIGHT_PX * CROP_ASPECT_WIDTH // CROP_ASPECT_HEIGHT

DEFAULT_HAS_BOX = True
BOX_OUTLINE_COLOR = "red"
BOX_OUTLINE_WIDTH = 2

BD_OUTPUT_SUFFIX = "bd"
AC_OUTPUT_SUFFIX = "ac"
