CROP_WIDTH_TO_TARGET_BOX_DIAGONAL = 3
CROP_ASPECT_WIDTH = 9
CROP_ASPECT_HEIGHT = 16

DEFAULT_HAS_BOX = True
BOX_OUTLINE_COLOR = "red"
BOX_OUTLINE_WIDTH = 2

BD_OUTPUT_SUFFIX = "bd"
AC_OUTPUT_SUFFIX = "ac"
